### ISSUE TITLE
Doesn't connect if options[:host] != default_options[:host]

### ISSUE THREAD

**Issue by tommyalvarez** [johnae/sambal#31]
If the host is different from the default_options -> 127.0.0.1... it fails to connect because the option flags is constructed as:

`option_flags = "-W \"#{options[:domain]}\" -U \"#{options[:user]}\" -I #{options[:ip_address]} -p #{options[:port]}"`

and since options[:ip_address] is blank, it will fail. I tested manually and removing the -I entirely makes it work again. Adding a conditional t o include -I options[:ip_address] only when options[:ip_address].present? should fix the problem.

**Comment by johnae** [comment]
Should be fixed in latest master.
