### ISSUE TITLE
Smbclient response when trying to cd to a non-existing directory

### ISSUE THREAD

**Issue by np422** [johnae/sambal#54]
When the version of smbclient I use tries to cd to a non existing directory it will respond with NT_STATUS_OBJECT_PATH_NOT_FOUND.

The Client#cd method searches for the string NT_STATUS_OBJECT_NAME_NOT_FOUND in the response

A regex that tries to find both is used in pull request https://github.com/johnae/sambal/pull/53

**Comment by johnae** [comment]
Merged https://github.com/johnae/sambal/pull/53
